name: Test and Lint

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Pnpm package manager
              run: |
                npm install -g pnpm

            - name: Install Dependencies
              run: pnpm install 
            
            - name: Run Lint
              run: pnpm lint

            - name: Run Test
              run: pnpm test
        